[package]
name = "utilities"
version = "0.1.0"
authors = ["Yann Hamdaoui <yann.hamdaoui@gmail.com>"]
edition = "2018"

[lib]
bench = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = {path = "../"}
criterion = "0.3"
codespan = "0.11"
