name: "Update Rust channels"
on:
  pull_request:
  schedule:
  - cron: '1 1 * * *'
jobs:

  update-rust-channels:

    strategy:
      matrix:
        rust_channel:
        - stable
        - beta
        - nightly

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Add `unstable` Nix channel
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing nixFlakes
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    # TODO:
    # - uses: cachix/cachix-action@v8
    #   with:
    #     name: nickel
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Update `${{ matrix.rust_channel }}` channel
      run: |
        bash ./scripts/update_channel.sh ${{ matrix.rust_channel }}

    - name: Build Nickel against `${{ matrix.rust_channel }}` Rust channel
      run: |
        nix build ./#checks.x86_64-linux.nickel-against-${{ matrix.rust_channel }}-rust-channel

    - name: Commit `scripts/channel_${{ matrix.channel }}.toml`
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update `${{ matrix.channel }}` Rust channel [ci skip]'
        branch: 'master'
        file_pattern: scripts/channel_${{ matrix.channel }}.toml
        # See https://github.community/t/github-actions-bot-email-address/17204/6
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions
      if: github.repository == 'tweag/nickel'
