name: "Update Rust channels"
on:
  schedule:
  - cron: '1 1 * * *'
jobs:

  update-rust-channels:

    strategy:
      # Run in sequence to prevent `git push` overlaps
      max-parallel: 1
      matrix:
        rust_channel:
        - stable
        - beta
        - nightly

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nickel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Update `${{ matrix.rust_channel }}` channel
      run: |
        bash ./scripts/update_channel.sh ${{ matrix.rust_channel }}

    - name: Build Nickel against `${{ matrix.rust_channel }}` Rust channel
      run: |
        nix build ./#checks.x86_64-linux.nickel-against-${{ matrix.rust_channel }}-rust-channel

    - name: Commit `scripts/channel_${{ matrix.rust_channel }}.toml`
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update `${{ matrix.rust_channel }}` Rust channel [ci skip]'
        branch: 'master'
        file_pattern: scripts/channel_${{ matrix.rust_channel }}.toml
        # See https://github.community/t/github-actions-bot-email-address/17204/6
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
      if: github.repository == 'tweag/nickel'
