name: Website
on:
  pull_request:
  push:
    branches:
      - "master"
jobs:
  deploy-to-netlify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Installing Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: nickel
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the Nickel WASM REPL
        run: |
          nix build ./#buildWasm

      - name: Update the nickel-repl node package
        run: |
          rm -rf website/nickel-repl
          cp -r result/nickel-repl website/

      - run: npm ci --only=production
        working-directory: website/

      - run: |
          npm run build
          cp netlify.toml public/
        working-directory: website/

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          production-branch: 'master'
          production-deploy: ${{ github.event_name == 'push' }}
          publish-dir: './website/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
        if: github.repository == 'tweag/nickel'
