name: Website
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd website/
      - run: npm ci --only=production
      - run: npm run build
      - name: Deploy to Netlify
        id: deploy
        run: |
          [[ "$GITHUB_REF" == "refs/heads/master" ]] && flags=--prod
          # Awk is required because netlify outputs some warnings on stdout.
          npx netlify deploy $flags --json | awk "/{/,/}/" | tee result.json
          echo "::set-output name=deploy_url::$(jq -r .deploy_url result.json)"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Add commit status
        uses: Sibz/github-status-action@v1.1.0
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          context: deploy/netlify
          description: Deploy preview ready
          state: success
          target_url: ${{ steps.deploy.outputs.deploy_url }}
